#!/usr/bin/env swift
import Foundation

#if canImport(Darwin)
    import Darwin
#else
    import Glibc
#endif

func fail(_ message: String) -> Never {
    FileHandle.standardError.write(Data("generate_localizations: \(message)\n".utf8))
    exit(EXIT_FAILURE)
}

func loadKeys(from url: URL) throws -> Set<String> {
    let data = try Data(contentsOf: url)
    let propertyList = try PropertyListSerialization.propertyList(from: data, options: [], format: nil)
    guard let strings = propertyList as? [String: String] else {
        throw NSError(domain: "LocalizationGenerator", code: 1, userInfo: [
            NSLocalizedDescriptionKey: "Expected a string dictionary in \(url.path)"
        ])
    }
    return Set(strings.keys)
}

let swiftReservedWords: Set<String> = [
    "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func", "import", "init",
    "inout", "internal", "let", "operator", "private", "protocol", "public", "static", "struct",
    "subscript", "typealias", "var", "break", "case", "continue", "default", "defer", "do", "else",
    "fallthrough", "for", "guard", "if", "in", "repeat", "return", "throw", "switch", "where", "while",
    "as", "Any", "catch", "false", "is", "nil", "rethrows", "super", "self", "Self", "true", "try",
    "_", "#available", "#colorLiteral", "#column", "#else", "#elseif", "#endif", "#error", "#file",
    "#fileID", "#filePath", "#function", "#if", "#imageLiteral", "#line", "#selector", "#sourceLocation",
    "#warning", "async", "await", "actor", "any", "borrowing", "consuming", "distributed", "each",
    "macro", "nonisolated", "package", "sending", "some"
]

func swiftIdentifier(for key: String) -> String {
    let parts = key.split(whereSeparator: { !$0.isLetter && !$0.isNumber })
    guard !parts.isEmpty else { return "" }
    let words = parts.enumerated().map { index, part in
        let value = String(part)
        let first = String(value.prefix(1))
        let remainder = String(value.dropFirst())
        return (index == 0 ? first.lowercased() : first.uppercased()) + remainder
    }
    let identifier = words.joined()
    guard swiftReservedWords.contains(identifier) else { return identifier }
    return "key" + identifier.prefix(1).uppercased() + identifier.dropFirst()
}

func swiftStringLiteral(_ value: String) -> String {
    let escaped = value
        .replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"")
    return "\"\(escaped)\""
}

let arguments = Array(CommandLine.arguments.dropFirst())
guard arguments.isEmpty || arguments == ["--check"] else {
    fail("usage: swift Tools/generate_localizations.swift [--check]")
}

let scriptURL = URL(fileURLWithPath: #filePath)
let rootURL = scriptURL.deletingLastPathComponent().deletingLastPathComponent()
let englishURL = rootURL.appendingPathComponent("macos/en.lproj/Localizable.strings")
let japaneseURL = rootURL.appendingPathComponent("macos/ja.lproj/Localizable.strings")
let outputURL = rootURL.appendingPathComponent("Sources/WaddlyApp/LocalizationKey.generated.swift")

let englishKeys: Set<String>
let japaneseKeys: Set<String>
do {
    englishKeys = try loadKeys(from: englishURL)
    japaneseKeys = try loadKeys(from: japaneseURL)
} catch {
    fail(error.localizedDescription)
}

let missingFromJapanese = englishKeys.subtracting(japaneseKeys).sorted()
let missingFromEnglish = japaneseKeys.subtracting(englishKeys).sorted()
if !missingFromJapanese.isEmpty || !missingFromEnglish.isEmpty {
    let details = [
        missingFromJapanese.isEmpty ? nil : "missing from ja: \(missingFromJapanese.joined(separator: ", "))",
        missingFromEnglish.isEmpty ? nil : "missing from en: \(missingFromEnglish.joined(separator: ", "))"
    ].compactMap(\.self).joined(separator: "; ")
    fail("English and Japanese localization keys differ (\(details))")
}

let sortedKeys = englishKeys.sorted()
let identifiers = sortedKeys.map { ($0, swiftIdentifier(for: $0)) }
guard identifiers.allSatisfy({ !$0.1.isEmpty && $0.1.first?.isLetter == true }) else {
    fail("a localization key could not be converted to a Swift identifier")
}

let identifierGroups = Dictionary(grouping: identifiers, by: { $0.1 })
let collisions = identifierGroups.filter { $0.value.count > 1 }
if !collisions.isEmpty {
    let names = collisions.keys.sorted().joined(separator: ", ")
    fail("localization keys produce duplicate Swift accessors: \(names)")
}

let accessors = identifiers.map { pair in
    "    case \(pair.1) = \(swiftStringLiteral(pair.0))"
}.joined(separator: "\n")
let generated = """
// Generated by Tools/generate_localizations.swift. Do not edit.

enum LocalizationKey: String, CaseIterable {
\(accessors)
}
""" + "\n"

if arguments == ["--check"] {
    guard let current = try? String(contentsOf: outputURL, encoding: .utf8), current == generated else {
        fail("generated accessors are stale; run swift Tools/generate_localizations.swift")
    }
    print("Localization accessors are up to date.")
} else {
    do {
        try generated.write(to: outputURL, atomically: true, encoding: .utf8)
    } catch {
        fail(error.localizedDescription)
    }
    print("Generated \(outputURL.path)")
}
